'use client';

import type { City } from '@/lib/cities';
import { predefinedCities } from '@/lib/cities';
import CitySelector from './CitySelector';
import CityCard from './CityCard';
import Feature from './Feature';

interface LandingPageProps {
  onCitySelect: (city: City) => void;
  onTeleport: () => void;
}

export default function LandingPage({ onCitySelect, onTeleport }: LandingPageProps) {
  // Select diverse cities from different regions
  const featuredCities = [
    predefinedCities.find(c => c.name === "New York")!,
    predefinedCities.find(c => c.name === "London")!,
    predefinedCities.find(c => c.name === "Tokyo")!,
    predefinedCities.find(c => c.name === "Paris")!,
    predefinedCities.find(c => c.name === "Sydney")!,
    predefinedCities.find(c => c.name === "Dubai")!,
    predefinedCities.find(c => c.name === "Bengaluru")!,
    predefinedCities.find(c => c.name === "São Paulo")!,
  ].filter(Boolean);
  
  return (
    <div className="min-h-[calc(100vh-80px)] flex flex-col">
      
      {/* Hero */}
      <section className="flex-1 flex items-center justify-center px-6 py-12">
        <div className="max-w-5xl mx-auto text-center space-y-8">
          
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-light text-sm text-white/70">
            <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
            Live weather from major world cities
          </div>
          
          {/* Main Headline */}
          <h1 className="text-6xl md:text-8xl lg:text-9xl font-serif leading-[1.2] tracking-tight pb-4">
            <span className="block text-white/90">Weather,</span>
            <span className="block text-gradient-warm italic pb-2">reimagined.</span>
          </h1>
          
          {/* Subheadline */}
          <p className="text-xl md:text-2xl text-white/50 max-w-2xl mx-auto font-light leading-relaxed">
            Experience any city through stunning AI-generated isometric worlds powered by <span className="text-white/70 font-medium">nano-banana</span> and <span className="text-white/70 font-medium">Gemini</span>. 
            Real weather. Real art. Real magic.
          </p>
          
          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
            <button 
              onClick={onTeleport}
              className="group relative px-8 py-4 rounded-full bg-gradient-to-r from-orange-500 via-amber-500 to-orange-500 bg-[length:200%_100%] text-white font-semibold text-lg shadow-xl transition-all duration-500 hover:shadow-orange-500/40 hover:bg-right animate-shimmer"
            >
              <span className="relative z-10 flex items-center gap-2">
                Take me anywhere
                <svg className="w-5 h-5 transition-transform group-hover:translate-x-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg>
              </span>
            </button>
            
            <div className="text-white/30 text-sm">or pick a city below</div>
          </div>
        </div>
      </section>

      {/* City Grid */}
      <section className="px-6 pb-12">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {featuredCities.map((city, i) => (
              <CityCard key={city.name} city={city} index={i} onClick={() => onCitySelect(city)} />
            ))}
          </div>
        </div>
      </section>

      {/* Search Bar */}
      <section className="px-6 pb-20">
        <div className="max-w-3xl mx-auto">
          <CitySelector onCitySelect={onCitySelect} selectedCity={null} />
        </div>
      </section>

      {/* Features Strip */}
      <section className="border-t border-white/5 py-16 px-6">
        <div className="max-w-6xl mx-auto grid md:grid-cols-3 gap-12">
          <Feature 
            icon="◉" 
            title="Real-time Data" 
            desc="Live weather synced with local timezones worldwide"
          />
          <Feature 
            icon="◈" 
            title="AI Artistry" 
            desc="Unique isometric scenes generated by Google Gemini"
          />
          <Feature 
            icon="◇" 
            title="Compare Views" 
            desc="Side-by-side city comparisons at a glance"
          />
        </div>
        
        {/* Model Disclaimer */}
        <div className="mt-12 text-center">
          <p className="text-xs text-white/30">
            Currently using <span className="text-white/50">Gemini 2.5 Flash</span>. 
            For higher quality results, try <span className="text-white/50">Gemini 3</span>.
          </p>
        </div>
        
        {/* Attribution */}
        <div className="mt-8 text-center">
          <p className="text-sm text-white/40">
            Powered by <span className="text-white/60 font-medium">nano-banana</span> and <span className="text-white/60 font-medium">Gemini Image Models</span>
          </p>
        </div>
      </section>
    </div>
  );
}

